#!/usr/bin/python
from tqdm import tqdm
from sys import stderr
stderr.write('stderr 测试 out with \\n\n')
stderr.write('stderr out with \\r. This shouldn\'t be visible.\r')
for i in tqdm(range(int(9e6))):
    pass
stderr.write('stderr out! \n')