#!/bin/bash

#* Presquite - Checking Python version
repo="greats3an/cmus-ncm"
interpreter=($1 'python3' 'python')
# Use the first argument as optional interper
executables=('cmus-ncm' 'live-lyrics')
# What executable to install?
function get_python() {
    if [[ ! -n $1 ]]; then
        echo $(get_python 0)
        exit
    fi
    if [[ ! -n ${interpreter[$1]} ]]; then
        echo ''
        exit
    fi
    if [[ -n $(command -v ${interpreter[$1]}) ]]; then
        echo ${interpreter[$1]}
    else
        index=$1
        ((index++))
        echo $(get_python $index)
    fi
}

interpreter=$(get_python)
if [[ ! -n $interpreter ]]; then
    echo [!] No Python interpreter is currently deteced
    echo [-] Install Python 3 to your OS,then run this script again
    exit
fi
# No interpreter is deteced
if [[ ! $(${interpreter} -V) == *"Python 3"* ]]; then
    echo [!] The installed interpreter \($(${interpreter} -V)\) does not meet script requirement
    echo [-] You need to install Python 3 to continue
    exit
fi
# interpreter is not Python 3

#* Installing PyNCM

echo [-] Detected Python version \: $(${interpreter} -V) \(${interpreter}\)
echo [-] Installing PyNCM

if ! ${interpreter} -m pip install -U pyncm ; then 
    echo [!] The module did not get installed correctly
    echo [-] Check if 'pip' was installed.The script will exit now
    exit
fi

#* Aqquiring the script

# Selecting an executbale
echo [-] Choose an executable to install \(see README.md for more info\)
select executable in ${executables[@]}; do
if [[ ! -n $executable ]] ; then 
    echo [!] Bad selection! The script will exit now
    exit 1
fi
echo [+] Installing ${executable}
break
done

# Try to download the script
echo "[+] Downloading ${executable} form its repo"
if ! curl -o ${executable} https://raw.githubusercontent.com/${repo}/master/${executable} ; then
    echo "[!] Failed to download the script using 'curl'!"
    echo "[!] You may want to download the script manualy through the github page"
    exit
fi
echo "[+] Successfully downloaded the script"

#! Installing the script
python_executable=`${interpreter} -c "import sys;print(sys.executable)"`
(echo "#!${python_executable}" && cat ${executable}) > ${executable}-temp
# Create a tempoary file for adding the executable path to script

echo "[-] Modifing permissions"
chmod +x ${executable}-temp

echo "[!] '${executable}' will be copied to '/usr/local/bin'"

if ! cp ${executable}-temp /usr/local/bin/${executable} ; then
    echo "[!] Cannot copy as current user"
    echo "[!] Trying to copy with 'sudo' "
    if ! sudo cp ${executable}-temp /usr/local/bin/${executable} ; then
        echo "[!] Failed to copy with 'sudo'"
        echo "[-] You may want run this script as 'root' or change ownership of '/usr/local/bin' to continue"
        exit
    fi
fi
echo "[-] Successfully copied the script"

#* Finishing up
# Removes old file
rm ${executable}-temp
echo "[+] The script is successfully installed"
echo "[-] You may check https://github.com/${repo} for usage and support"
