#!/bin/bash

#* Presquite - Checking Python version
repo="http://github.com/greats3an/cmus-ncm"
interpreter=($1 'python3' 'python')
# Use the first argument as optional interper
function get_python() {
    if [[ ! -n $1 ]]; then
        echo $(get_python 0)
        exit
    fi
    if [[ ! -n ${interpreter[$1]} ]]; then
        echo ''
        exit
    fi
    if [[ -n $(command -v ${interpreter[$1]}) ]]; then
        echo ${interpreter[$1]}
    else
        index=$1
        ((index++))
        echo $(get_python $index)
    fi
}

interpreter=$(get_python)
if [[ ! -n $interpreter ]]; then
    echo [!] No Python interpreter is currently deteced
    echo [-] Install Python 3 to your OS,then run this script again
    exit
fi
# No interpreter is deteced
if [[ ! $(${interpreter} -V) == *"Python 3"* ]]; then
    echo [!] The installed interpreter \($(${interpreter} -V)\) does not meet script requirement
    echo [-] You need to install Python 3 to continue
    exit
fi
# interpreter is not Python 3

#* Installing PyNCM

echo [-] Detected Python version \: $(${interpreter} -V) \(${interpreter}\)
echo [-] Installing PyNCM

if ! ${interpreter} -m pip install -U pyncm ; then 
    echo [!] The module did not get installed correctly
    echo [-] Check if 'pip' was installed.The script will exit now
    exit
fi

#* Aqquiring the script
if [[ -f "cmus-ncm" ]];then
    echo "[+] C* NCM Script already located!"
else
    # Try to download the script
    echo "[+] Downloading cmus-ncm form its repo"
    if ! curl -o cmus-ncm  https://raw.githubusercontent.com/greats3an/cmus-ncm/master/cmus-ncm ; then
        echo "[!] Failed to download the script using 'curl'!"
        echo "[!] You may want to download the script manualy through the github page"
        exit
    fi
    echo "[+] Successfully downloaded the script"
fi

#! Installing the script
python_executable=`${interpreter} -c "import sys;print(sys.executable)"`
(echo "#!${python_executable}" && cat cmus-ncm) > cmus-ncm-temp
# Create a tempoary file for adding the executable path to script

echo "[-] Modifing permissions"
chmod +x cmus-ncm-temp

echo "[!] 'cmus-ncm' will be copied to '/usr/local/bin'"

if ! cp cmus-ncm-temp /usr/local/bin/cmus-ncm ; then
    echo "[!] Cannot copy as current user"
    echo "[!] Trying to copy with 'sudo' "
    if ! sudo cp cmus-ncm-temp /usr/local/bin/cmus-ncm ; then
        echo "[!] Failed to copy with 'sudo'"
        echo "[-] You may want run this script as 'root' or change ownership of '/usr/local/bin' to continue"
        exit
    fi
fi
echo "[-] Successfully copied the script"

#* Finishing up
# Removes old file
rm cmus-ncm-temp
echo "[+] The script is successfully installed"
echo "[-] You may check ${repo} for usage and support"
